name: Release

on:
  push:
    branches:
      - main

jobs:

  Release:
    # prevents this action from running on forks
    if: github.repository == 'manzt/reference-spec-reader'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: pnpm install --frozen-lock

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
